services:
  invoice-reminder:
    build:
      context: .  
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
