services:
  invoice-reminder:
    build:
      context: .  
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_PROFILES_ACTIVE=
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - MESSAGES_WHATSAPP_URL=
      - MESSAGES_WHATSAPP_TOKEN=
      - INVOICE_BASE_URL=
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
