services:
  invoice-reminder:
    build:
      context: .  
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
