version: '3.8'

services:
  invoice-reminder:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: invoice-reminder
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8080:8080"  
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge